version: "3.9"

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_DB=event-manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Secret125
      - JWT_SECRET=Secret125
      - JWT_ALGORITHM=HS256
