CREATE TABLE users (
	user_id INT GENERATED ALWAYS AS IDENTITY,
	username VARCHAR(20) NOT NULL,
	email VARCHAR(30) NOT NULL,
	password VARCHAR(50) NOT NULL,
	PRIMARY KEY(user_id)
);

DROP TABLE users;

SELECT * FROM users;